### ISSUE TITLE
Default magenta folder highlighting too distracting

### ISSUE THREAD

**Issue by MatthewScholefield** [zdharma/fast-syntax-highlighting#84]
This is just a matter of opinion, but I'm creating this issue in case anyone else agrees. It's super-awesome that it's configurable, but I think it would be better for new user's as something subtler like a white-underline (which is slightly brighter than default text).

Note: if anyone else finds the old default better and doesn't want to mess with themes, you can switch to it via:
```bash
cd ~/.oh-my-zsh/custom/plugins/fast-syntax-highlighting  # Or wherever the git clone is for your installation
git checkout edaef2  # Commit before magenta change
```

**Comment by psprint** [comment]
The commit edaef2b seems to not withdraw magenta for paths.

I agree the color is distracting (or that it attracts attention), it was my decision to use color instead of underline because when I'm using command-line, I'm highly hmm.. distracted? quick and do not pay attention to such subtle things like the underline. So I wanted an explicit message "this is a path". That's the history behind this, I can see other users having different usage practice and opting for the underline.

I would change this as follows:

1. Create `~/.config/fsh/overlay.ini` by:
   - `mkdir -p ~/.config/fsh`
   - `echo 'path = white,underline' >| ~/.config/fsh/overlay.ini`
2. Set up the overlay by issuing: `fast-theme XDG:overlay`.

That's it. Adding another line `path-to-dir = white,bold,underline` will change style for paths that are directories. The overlay will be active for any theme being set up, use `fast-theme -R` to disable current overlay.
